# Based on https://github.com/plexinc/pms-docker/blob/master/docker-compose-bridge.yml.template
version: "2"
services:
  plex:
    container_name: plex
    # note: not specifying a version here so docker selects the right image.
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=US/Pacific
      ###########################################################################
      # TODO: Get a new PLEX_CLAIM code when setting up new instance/config dir
      #       at https://www.plex.tv/claim/
      - PLEX_CLAIM=<claimToken>
      ###########################################################################
      - ADVERTISE_IP=http://10.1.111.16:32400/
    hostname: plex-docker-bitbox
    devices:
      # Intel Quick Sync hardware acceleration for plex:
      # - https://github.com/plexinc/pms-docker#intel-quick-sync-hardware-transcoding-support
      # QNAP's Itel J4125 has it: https://www.intel.com/content/www/us/en/products/sku/197305/intel-celeron-processor-j4125-4m-cache-up-to-2-70-ghz/specifications.html
      - /dev/dri:/dev/dri
    volumes:
      #- <path/to/plex/database>:/config
      - /share/CACHEDEV1_DATA/app-data/plex/config:/config
      #- <path/to/transcode/temp>:/transcode
      - /share/CACHEDEV1_DATA/provisional/app-data/plex:/transcode
      #- <path/to/media>:/data
      - /share/CACHEDEV1_DATA/audio/Audiobooks:/data/Audiobooks
      - /share/CACHEDEV1_DATA/audio/Music:/data/Music
      - /share/CACHEDEV1_DATA/video/Movies:/data/Movies
      - /share/CACHEDEV1_DATA/video/TV-Shows:/data/TV-Shows
