# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
cover garage: !include cover-garage.yaml
lovelace: !include ui-lovelace-config.yaml

homeassistant:
  customize: !include customize.yaml
  
  packages:
    # packages: https://www.home-assistant.io/docs/configuration/packages/
    security_package: !include packages/security.yaml
    lights_package: !include packages/lights.yaml

# Setup certificates via the HTTP integration/component
# https://www.home-assistant.io/integrations/http:
http:
  ssl_certificate: /etc/letsencrypt/live/activescott.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/activescott.com/privkey.pem

# Notify Groups:
## See https://www.home-assistant.io/integrations/notify.group/
notify:
  - name: scott
    platform: group
    services:
      - service: mobile_app_fatboy
