# NOTE: the default dashboard must be named ui-lovelace.yaml in the root config dir.
title: Home
views:
  - path: default_view
    title: View
    cards:
      - title: Security
        show_name: true
        show_icon: true
        show_state: true
        type: glance
        entities:
          - entity: binary_sensor.perimeter_sensors
            tap_action:
              action: navigate
              navigation_path: /lovelace-alarm/0
          - entity: binary_sensor.motion_sensors
            tap_action:
              action: navigate
              navigation_path: /lovelace-alarm/0
        state_color: true
      - type: entities
        entities:
          - entity: scene.tv_lights
          - entity: scene.nightime_lights
          - entity: scene.great_room_bright
      - type: custom:auto-entities
        card:
          type: entities
          title: Common Area Lights
          state_color: true
        filter:
          include:
            - group: light.common_area_lights
          exclude: []
        sort:
          method: friendly_name
      - type: entities
        entities:
          - cover.garage_door
        state_color: true
      - type: custom:auto-entities
        card:
          type: entities
          title: Bedroom Lights
          state_color: true
        filter:
          include:
            - group: light.bedroom_lights
          exclude: []
        sort:
          method: friendly_name
      - type: custom:auto-entities
        card:
          type: entities
          title: Outdoor Lights
          state_color: true
        filter:
          include:
            - group: light.outdoor_lights
          exclude: []
        sort:
          method: friendly_name
      - type: entities
        entities:
          - entity: group.family_presence
            icon: mdi:human-male-female-child
            secondary_info: last-changed
          - entity: person.scott_willeke
            secondary_info: last-changed
          - entity: person.oksana
            secondary_info: last-changed
          - entity: person.jonah
            secondary_info: last-changed
          - entity: person.micah
            secondary_info: last-changed
        title: Person
        state_color: true
      - hours_to_show: 72
        graph: line
        type: sensor
        entity: sensor.lumi_lumi_weather_4c47b206_temperature
        detail: 1
        name: Office Temp
      - type: weather-forecast
        entity: weather.home8027
        show_forecast: false
      - type: entities
        entities:
          - entity: sensor.cert_expiry_timestamp_hass_activescott_com_8123
            name: hass cert expires
          - entity: sensor.cert_expiry_timestamp_scott_willeke_com
            name: scott.willeke.com cert expires
      - type: entities
        entities:
          - entity: sensor.alarm_panel_display
