resources:
  - ./overlays/scott

buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: cert-manager
