resources:
  - ./namespace.yaml
  - ./base/mariadb-statefulset.yaml
  - ./base/mariadb-service.yaml

  - ./base/photoprism-statefulset.yaml
  - ./base/photoprism-service.yaml
  - ./base/photoprism-ingress.yaml

namespace: photoprism

buildMetadata: [managedByLabel]

labels:
  - pairs:
      deployedBy: scott-via-kustomize
