# Reference:
# - https://cert-manager.io/docs/concepts/certificate/
# - https://cert-manager.io/docs/usage/certificate/
# - tutorial: https://cert-manager.io/docs/tutorials/acme/nginx-ingress/
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hass-activescott-com
  namespace: home-assistant
spec:
  # the secret is put here:
  secretName: hass-activescott-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: hass.activescott.com
  dnsNames:
  - hass.activescott.com
