resources:
  - ./certificate.yaml
  - ./grafana-ingress.yaml
  - ./grafana-service.yaml
  - ./grafana-statefulset.yaml

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: grafana
  # NOTE: tenet is specified in the overlays
  #app.activescott.com/tenant: 
