apiVersion: v1
kind: Pod
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    ports:
      - name: dummy
        containerPort: 80
      
    resources:
      limits:
        cpu: "0.2"
        memory: "256Mi"
      requests:
        cpu: "0.2"
        memory: "256Mi"
