resources:
  - ./authorize-prometheus-to-k8s.yaml
  - ./prometheus-statefulset.yaml
  - ./prometheus-service.yaml
  - ./certificate.yaml
  - ./prometheus-ingress.yaml  

# kustomize help on configMapGenerator: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_configmapgenerator_
configMapGenerator:
  - name: prometheus-config
    files:
    - prometheus.yml
    # I found we can scrape erigon using the pod scraper with some annotations
    # - erigon.scrape_config.yml=scrape_config_files/erigon.scrape_config.yml

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: prometheus
  # NOTE: tenet is specified in the overlays
  #app.activescott.com/tenant: 
