apiVersion: v1
kind: Service
metadata:
  name: ethlodestar
  namespace: eth
  labels:
    app: eth
    role: consensus-client
spec:
  # NOTE: Using NodePort to allow EXTERNAL traffic to be forwarded to pod's port.
  #       ...because Ingress is HTTP only and doesn't support raw UDP/TCP-level forwarding.
  type: NodePort
  
  selector:
    app: eth
    role: consensus-client
  
  ports:
    - name: eth-consensus-p2p
      port: 9000
      nodePort: 9000
    
    - name: eth-consensus-rpc
      port: 9596
      nodePort: 9596
