apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: blackbox-exporter

  template:
    metadata:
      labels:
        app: blackbox-exporter

    spec:
      containers:
      - name: blackbox-exporter
        # image tags at https://quay.io/repository/prometheus/blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:v0.25.0
        args:
        - '--config.file=/config/blackbox-config.yaml'
        
        ports:
        - name: for-prometheus
          containerPort: 9115

        resources:
          limits:
            cpu: "1.0"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "250Mi"
      
        volumeMounts:
        # per https://github.com/prometheus/blackbox-exporter?tab=readme-ov-file#using-the-docker-image
        - name: blackbox-exporter-config-volume
          mountPath: /config
        
      volumes:
      # populated by configMapGenerator in kustomization.yaml
      - name: blackbox-exporter-config-volume
        configMap:
            defaultMode: 420
            name: blackbox-exporter-config
