resources:
  - ./blackbox-deployment.yaml
  - ./blackbox-service.yaml

configMapGenerator:
  # the blackbox exporter's config:
  - name: blackbox-exporter-config
    files:
    - ./config/blackbox-config.yaml

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: blackbox-exporter
