apiVersion: v1
kind: Service
metadata:
    name: alertmanager

spec:
  # Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from within the cluster
  # we don't expose this workload publicly, and the service really only is used to keep the IP more stable as pods bounce
  type: ClusterIP
  ports:
    - name: api
      port: 9093
      # targetPort name/port matches the container
      targetPort: api
  selector:
    app: alertmanager
    
