resources:
  - ./alertmanager-deployment.yaml
  - ./alertmanager-service.yaml

configMapGenerator:
  # the alertmanager's config:
  - name: alertmanager-config
    files:
    - ./config/alertmanager.yaml
    # contains the raw secret to the telegram bot
    - ./config/telegram_bot_token.secret

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: alertmanager
