version: '3'
services:
  zwavejs:
    #build:
    #  context: .
    #  dockerfile: zwave-js-server.Dockerfile
    # TODO: use the explicit tag/version so that editing the docker-compose file in QNAP Container Station will force it to pull a new image:
    image: activescott/zwave-js-server:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      # Z-Wave cache on QNAP 
      #- ./cache:/cache
      - /share/CACHEDEV1_DATA/app-data/home-assistant-zwave-js/cache:/cache
      # Z-Wave cache on local dev:
      #- ./cache:/cache
      # zwave-js config on QNAP
      - /share/CACHEDEV1_DATA/app-data/home-assistant-zwave-js/config:/config
      # zwave-js config on local dev
      #- ./config-zwave-js:/config
    devices:
      # QNAP zwave (note the /dev/zwave is configured in the Dockerfile/image)
      - /dev/ttyUSB0:/dev/zwave
      # dev (macOS w/ Silicon Labs' CP210x USB to UART Bridge VCP Drivers):
      #- '/dev/tty.GoControl_zwave:/dev/zwave'
  
  homeassistant:
    container_name: homeassistant
    # NOTE: using the explicit tag/version so that editing the docker-compose file in QNAP Container Station will force it to pull a new image:
    image: homeassistant/home-assistant:2021.5.5
    restart: unless-stopped
    network_mode: host
    volumes:
      # Use host's time:
      - /etc/localtime:/etc/localtime:ro
      # Config on QNAP:
      - /share/CACHEDEV1_DATA/app-data/home-assistant:/config
      # Config on dev:
      #- ./config-home-assistant:/config
    devices:
      # QNAP zigbee?
      - /dev/ttyUSB1:/dev/ttyUSB1
