apiVersion: v1
kind: PersistentVolume
metadata:
  name: oksana-wordpress-mariadb-pv
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # https://kubernetes.io/docs/concepts/storage/volumes/#local
  local:
    path: /mnt/thedatapool/app-data/wordpress-oksana/mariadb-data
  # NOTE: must set a PersistentVolume nodeAffinity when using local volumes
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ix-truenas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oksana-wordpress-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  # volumeName hard binds us to the PV above: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume
  volumeName: oksana-wordpress-mariadb-pv
  resources:
    requests:
      storage: 1Ti  