apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # https://kubernetes.io/docs/concepts/storage/volumes/#local
  local:
    path: /mnt/thedatapool/app-data/nextcloud/mariadb
  # NOTE: must set a PersistentVolume nodeAffinity when using local volumes
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ix-truenas
