resources:
  - ./namespace.yaml

# Kustomize helmCharts: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
helmCharts:
- name: traefik
  repo: https://traefik.github.io/charts
  version: v23.0.1
  namespace: traefik
  # traefik includes a `Middleware` CRD that we need
  includeCRDs: true
  # Traefik helm chart at https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  valuesInline:
    podAnnotations:
      # the prometheus config is configured to look for this
      prometheus.io/scrape: 'true'
    
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "2.0"
        memory: "1Gi"

    rbac:
      enabled: true
      #namespaced: false # false = allow traefik to be used across namespaces
    ports:
      websecure: # i.e. port 443
        tls:
          enabled: true
        ## -- Trust forwarded  headers information (X-Forwarded-*).
        forwardedHeaders:
          trustedIPs:
            - 10.1.111.20
          insecure: false
      web: # i.e. port 80
        # Port Redirections
        # Added in 2.2, you can make permanent redirects via entrypoints.
        # https://docs.traefik.io/routing/entrypoints/#redirection
        redirectTo: websecure
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true 

    ## TLS ##
    # mounting default cert vols like this in k8s just seemed ignored.
    #  Add volume to the pod; make available to containers:
    #deployment:
    #  additionalVolumes:
    #    - name: cert-activescott-com
    #      hostPath:
    #        path: /mnt/thedatapool/app-data/letsencrypt
    #        type: Directory
    # now add the volumeMount to the traefik container
    #additionalVolumeMounts:
    #  - name: cert-activescott-com
    #    mountPath: /etc/letsencrypt
    #    readOnly: true
    
    ## Set TLS at the entrypoint
    ## https://doc.traefik.io/traefik/routing/entrypoints/#tls
    tls:
      enabled: true    
      # setting certificates from files doesn't work. Docs said somewhere it's not permitted in k8s.
      #certificates:
      #  - certFile: /etc/letsencrypt/live/activescott.com/fullchain.pem
      #    keyFile: /etc/letsencrypt/live/activescott.com/privkey.pem
      
      # apparently required to prevent error "No store is defined to add the certificate"?
      stores:
        default: {}

    ## Disable route to the traefik dashboard:
    ingressRoute:
      dashboard:
        enabled: false
    ## LOGS ##
    logs:
      general:
        # By default, the level is set to ERROR.
        # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: INFO
      access:
        # -- To enable access logs
        enabled: false

namespace: traefik

buildMetadata: [originAnnotations, transformerAnnotations]

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: traefik
  app.activescott.com/tenant: everyone
