# kinda like: https://cert-manager.io/docs/tutorials/acme/nginx-ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: letsencrypt-staging-certificate-test
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - photos.scott.willeke.com
    secretName: photos-scott-willeke-com-tls
  rules:
  - host: photos.scott.willeke.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-certificateissuer-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-certificateissuer-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: test-certificateissuer-does-not-exist

