
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Setup certificates via the HTTP integration/component
# https://www.home-assistant.io/integrations/http:
http:
  ssl_certificate: /etc/letsencrypt/live/activescott.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/activescott.com/privkey.pem

# Notify Groups:
## See https://www.home-assistant.io/integrations/notify.group/
notify:
  - name: scott
    platform: group
    services:
      - service: mobile_app_fatboy

# In order to add the zooz switches to a "light group", we have to expose the switches as lights: https://www.home-assistant.io/integrations/light.switch/
# WHY THE HELL are the zooz switches `switch` not `light`?
light:
  - platform: switch
    name: Kitchen Light Switch Light
    entity_id: switch.z_wave_plus_700_series_s2_on_off_switch
  - platform: switch
    name: Dining Table Light Switch Light
    entity_id: switch.z_wave_plus_700_series_s2_on_off_switch_2
  - platform: switch
    name: Jonah's Lamp Switch Light
    entity_id: switch.jonahs_lamp_on_off
    # A set of lights to toggle during "vacation" while people are away
    # A Light Group entity to combine lights that should be toggled during "vacation mode" (while people are away at night-ish)
    # THIS SHIT DON'T WORK:
  - platform: group
    name: Vacation Lights
    entities:
      # Great Room Track Light 
      - light.z_wave_plus_700_series_s2_dimmer_switch
      # Kitchen Light
      - light.kitchen_light_switch_light
      # Dining Table Light:
      - light.dining_table_light_switch_light
      # Jonah's Lamp
      - light.jonah_s_lamp_switch_light
