
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Setup certificates via the HTTP integration/component
# https://www.home-assistant.io/integrations/http:
http:
  ssl_certificate: /etc/letsencrypt/live/activescott.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/activescott.com/privkey.pem
