# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml

homeassistant:
  customize: !include customize.yaml

# Setup certificates via the HTTP integration/component
# https://www.home-assistant.io/integrations/http:
http:
  ssl_certificate: /etc/letsencrypt/live/activescott.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/activescott.com/privkey.pem

# Notify Groups:
## See https://www.home-assistant.io/integrations/notify.group/
notify:
  - name: scott
    platform: group
    services:
      - service: mobile_app_fatboy

# Garage Door Integration
# Uses template platform to invoke services for each of the open, close, stop, position and tilt commands of a cover.
# See https://www.home-assistant.io/integrations/cover.template/#garage-door
cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garage Door"
        position_template: >-
          {% if states('binary_sensor.garage_door_sensor_device_access_control_window_door_is_open') == "off" %}
            0
          {% else %}
            100
          {% endif %}
        open_cover:
          - condition: state
            entity_id: binary_sensor.garage_door_sensor_device_access_control_window_door_is_open
            state: "off"
          - service: switch.toggle
            target:
              entity_id: switch.zwave_garage_relay
        close_cover:
          - condition: state
            entity_id: binary_sensor.garage_door_sensor_device_access_control_window_door_is_open
            state: "on"
          - service: switch.toggle
            target:
              entity_id: switch.zwave_garage_relay
        stop_cover:
          service: switch.toggle
          target:
            entity_id: switch.zwave_garage_relay
        icon_template: >-
          {% if states('binary_sensor.garage_door_sensor_device_access_control_window_door_is_open') == "off" %}
            mdi:garage
          {% else %}
            mdi:garage-open
          {% endif %}
