# Garage Door Integration
# Uses template platform to invoke services for each of the open, close, stop, position and tilt commands of a cover.
# See https://www.home-assistant.io/integrations/cover.template/#garage-door
- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      position_template: >-
        {% if states('binary_sensor.garage_door_sensor_device_access_control_window_door_is_open') == "off" %}
          0
        {% else %}
          100
        {% endif %}
      open_cover:
        - condition: state
          entity_id: binary_sensor.garage_door_sensor_device_access_control_window_door_is_open
          state: "off"
        - service: switch.toggle
          target:
            entity_id: switch.zwave_garage_relay
      close_cover:
        - condition: state
          entity_id: binary_sensor.garage_door_sensor_device_access_control_window_door_is_open
          state: "on"
        - service: switch.toggle
          target:
            entity_id: switch.zwave_garage_relay
      stop_cover:
        service: switch.toggle
        target:
          entity_id: switch.zwave_garage_relay
      icon_template: >-
        {% if states('binary_sensor.garage_door_sensor_device_access_control_window_door_is_open') == "off" %}
          mdi:garage
        {% else %}
          mdi:garage-open
        {% endif %}
    