title: Security
views:
  - title: View
    cards:
      - show_name: true
        show_icon: true
        show_state: true
        type: glance
        entities:
          - entity: cover.garage_door
          - entity: alarm_control_panel.alarm_panel
          - entity: binary_sensor.motion_sensors
      - type: custom:auto-entities
        card:
          type: entities
          title: Perimeter
          state_color: true
        filter:
          include:
            - group: binary_sensor.perimeter_sensors
          exclude: []
        sort:
          method: friendly_name
      - type: custom:auto-entities
        card:
          type: entities
          title: Motion
          state_color: true
        filter:
          include:
            - group: binary_sensor.motion_sensors
          exclude: []
        sort:
          method: friendly_name
      - type: alarm-panel
        states:
          - arm_home
          - arm_away
        entity: alarm_control_panel.alarm_panel
      - type: entities
        entities:
          - person.oksana
          - person.scott_willeke
        state_color: true
      - type: entities
        entities:
          - entity: sensor.alarm_panel_display
          - entity: alarm_control_panel.alarm_panel
          - type: attribute
            entity: alarm_control_panel.alarm_panel
            attribute: ready
            name: Ready
            icon: mdi:check
          - type: attribute
            entity: alarm_control_panel.alarm_panel
            attribute: alarm_event_occurred
            name: Alarm Event Occurred
            icon: mdi:exit-run
          - type: attribute
            entity: alarm_control_panel.alarm_panel
            attribute: battery_low
            name: Battery Low
            icon: mdi:battery
          - type: attribute
            entity: alarm_control_panel.alarm_panel
            attribute: ac_power
            name: AC Power
            icon: mdi:power
          - type: attribute
            entity: alarm_control_panel.alarm_panel
            attribute: check_zone
            name: Check Zone
            icon: mdi:alert
          - type: attribute
            entity: alarm_control_panel.alarm_panel
            attribute: chime
            name: Chime
            icon: mdi:bell
          - type: attribute
            entity: alarm_control_panel.alarm_panel
            attribute: zone_bypassed
            name: Zone Bypassed
            icon: mdi:lock-off

