version: '3'
services:
  zwavejs:
    #build:
    #  context: .
    #  dockerfile: zwave-js-server.Dockerfile
    # using the explicit tag/version so that editing the docker-compose file in QNAP Container Station will force it to pull a new image:
    image: activescott/zwave-js-server:release-1.0.0
    restart: unless-stopped
    network_mode: host
    volumes:
      # ZWave cache on QNAP
      - /share/CACHEDEV1_DATA/app-data/home-assistant-zwave-js/cache:/cache
      # ZWave-js config on QNAP
      - /share/CACHEDEV1_DATA/app-data/home-assistant-zwave-js/config:/config
    devices:
      # QNAP zwave (note the /dev/zwave is configured in the Dockerfile/image)
      - /dev/ttyUSB0:/dev/zwave
  
  homeassistant:
    container_name: homeassistant
    # NOTE: using the explicit tag/version so that editing the docker-compose file in QNAP Container Station will force it to pull a new image:
    image: homeassistant/home-assistant:2021.5.5
    restart: unless-stopped
    network_mode: host
    depends_on:
      - zwavejs
    volumes:
      # Use host's time:
      - /etc/localtime:/etc/localtime:ro
      # Config on QNAP:
      - /share/CACHEDEV1_DATA/app-data/home-assistant:/config
      # Config on dev:
      #- ./config-home-assistant:/config
    devices:
      # QNAP zigbee?
      - /dev/ttyUSB1:/dev/ttyUSB1
