version: "3"
services:
  #  zwavejs:
  #    container_name: homeassistant_zwavejs
  #    #build:
  #    #  context: .
  #    #  dockerfile: zwave-js-server.Dockerfile
  #    # using the explicit tag/version so that editing the docker-compose file in QNAP Container Station will force it to pull a new image:
  #    image: activescott/zwave-js-server:2021.8
  #    network_mode: host
  #    volumes:
  #      # ZWave cache on QNAP
  #      - /share/CACHEDEV1_DATA/app-data/home-assistant-zwave-js/cache:/cache
  #      # ZWave-js config on QNAP
  #      - /share/CACHEDEV1_DATA/app-data/home-assistant-zwave-js/config:/config
  #    devices:
  #      # QNAP zwave (note the /dev/zwave is configured in the Dockerfile/image)
  #      - /dev/ttyUSB0:/dev/zwave
  zwavejs2mqtt:
    # docs at https://zwave-js.github.io/zwavejs2mqtt/#/
    # repo at https://github.com/zwave-js/zwavejs2mqtt
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:5.8.0
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      # env docs at https://zwave-js.github.io/zwavejs2mqtt/#/guide/env-vars?id=environment-variables
      - SESSION_SECRET=ASWsessionSECRET
      # Uncomment if you want log times and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=US/Pacific
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - "/dev/ttyUSB0:/dev/zwave"
    volumes:
      # zwavejs2mqtt data store on QNAP
      - "/share/CACHEDEV1_DATA/app-data/home-assistant-zwavejs2mqtt/store:/usr/src/app/store"
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server

  homeassistant:
    container_name: homeassistant
    # NOTE: using the explicit tag/version so that editing the docker-compose file in QNAP Container Station will force it to pull a new image:
    # Dockerhub: https://hub.docker.com/r/homeassistant/home-assistant
    image: homeassistant/home-assistant:2021.7
    network_mode: host
    depends_on:
      - zwavejs2mqtt
    volumes:
      # Use host's time:
      - /etc/localtime:/etc/localtime:ro
      # Config on QNAP:
      - /share/CACHEDEV1_DATA/app-data/home-assistant:/config
      # Config on dev:
      #- ./config-home-assistant:/config
      # Certificates on QNAP:
      - /share/CACHEDEV1_DATA/app-data/letsencrypt:/etc/letsencrypt:ro
    devices:
      # QNAP zigbee?
      - /dev/ttyUSB1:/dev/ttyUSB1
