# Your Wi-Fi SSID and password
wifi_ssid: "NOWIFI"
wifi_password: "12345678"

# allow home assistant and ESPHome to connect to the device API with this key: https://esphome.io/components/api
# use like `key: !secret api_encryption_key`
api_encryption_key: "SECRET_HERE"

# enable ESPHome to to updates over ethernet: https://esphome.io/components/ota.html
ota_password: "SECRET_HERE"
