apiVersion: batch/v1
kind: CronJob
metadata:
  name: letsencrypt-secret-loader
spec:
  # daily at 12AM
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: letsencrypt-secret-loader-sa
          restartPolicy: OnFailure
          containers:
            - name: cert-renewal
              image: alpine:3.18
              env:
                - name: SECRET_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              command:
                - /bin/sh
                - -c
                - |
                  
                  if [[ -z "$SECRET_NAMESPACE" ]]; then
                    echo "ERROR: The SECRET_NAMESPACE environment variable is not specified or has an empty value. Set it to the value of the namespace where you want the secret to be created." >&2
                    exit 1
                  fi

                  echo "Creating the secret in SECRET_NAMESPACE '$SECRET_NAMESPACE'."

                  # Install kubectl
                  apk add --no-cache curl
                  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                  chmod +x kubectl
                  mv kubectl /usr/local/bin/

                  # Read the certificate files from the host and encode them as base64
                  #fullchain=$(cat /etc/letsencrypt/live/activescott.com/fullchain.pem | base64 -w 0)
                  #privkey=$(cat /etc/letsencrypt/live/activescott.com/privkey.pem | base64 -w 0)

                  # Update kubernetes secret value
                  #   Run this command again for each namespace:
                 
                  # note --dry-run=client + kubectl apply will also edit secret if it already exists.
                  kubectl create secret generic cert-activescott-com \
                    --namespace=$SECRET_NAMESPACE \
                    --type=kubernetes.io/tls \
                    --from-file=tls.crt=/etc/letsencrypt/live/activescott.com/fullchain.pem \
                    --from-file=tls.key=/etc/letsencrypt/live/activescott.com/privkey.pem \
                    --dry-run=client \
                    -o yaml \
                    | kubectl apply -f -

              volumeMounts:
                - name: cert-activescott-com
                  mountPath: /etc/letsencrypt
                  readOnly: true

          volumes:
            - name: cert-activescott-com
              hostPath:
                path: /mnt/thedatapool/app-data/letsencrypt
                type: Directory
