resources:
- ../../base
- certificate.yaml

patches:
- path: patch-mariadb-volume.yaml
- path: patch-photoprism-statefulset.yaml
- path: patch-photoprism-ingress.yaml

namePrefix: oksana-

commonLabels:
  app.activescott.com/tenant: oksana
