# Reference:
# - https://cert-manager.io/docs/concepts/certificate/
# - https://cert-manager.io/docs/usage/certificate/
# - tutorial: https://cert-manager.io/docs/tutorials/acme/nginx-ingress/
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photos-activescott-com
spec:
  # the secret is put here:
  secretName: photos-activescott-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: photos.activescott.com
  dnsNames:
  - photos.activescott.com
