resources:
  - ../../base
  # cert-manager-issued photos.scott.willeke.com
  - certificate-photos-scott-willeke-com.yaml
  # cert-manager-issued photos.activescott.com
  - certificate-photos-activescott-com.yaml
  
patches:
- path: patch-mariadb-volume.yaml
- path: patch-photoprism-statefulset.yaml
- path: patch-photoprism-ingress.yaml

namePrefix: scott-

commonLabels:
  app.activescott.com/tenant: scott
