resources:
- ./namespace.yaml
- ../../base

patches:
- patch-mariadb-statefulset.yaml
- patch-photoprism-statefulset.yaml
- patch-photoprism-ingress.yaml

namespace: photoprism-scott

nameSuffix: -scott
commonLabels:
  tenant: scott
