resources:
- ../../base
- certificate.yaml
# letsencrypt secret for photos.activescott.com
# TODO: move this to cert-manager
- ../../../letsencrypt-secret-loader

patches:
- patch-mariadb-volume.yaml
- patch-photoprism-statefulset.yaml
- patch-photoprism-ingress.yaml

namePrefix: scott-

commonLabels:
  app.activescott.com/tenant: scott
