resources:
  - ../../base
  - certificate.yaml
  # letsencrypt secret for photos.activescott.com
  # TODO: move this to cert-manager
  - ../../../letsencrypt-secret-loader

patches:
- path: patch-mariadb-volume.yaml
- path: patch-photoprism-statefulset.yaml
- path: patch-photoprism-ingress.yaml

namePrefix: scott-

commonLabels:
  app.activescott.com/tenant: scott
