resources:
- ./namespace.yaml
- ../../base
- ./photos.scott.willeke.com-certificate.yaml

patches:
- patch-mariadb-statefulset.yaml
- patch-photoprism-statefulset.yaml
- patch-photoprism-ingress.yaml

namespace: photoprism-scott

nameSuffix: -scott

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/tenant: scott