apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: photoprism-app
spec:
  template:
    spec:
      containers:
      # documentation : https://docs.photoprism.app/getting-started/docker-compose/
      - name: photoprism
        env:
        # mariadb name is changed by namePrefix kustomize transformer:
        - name: PHOTOPRISM_DATABASE_SERVER
          value: scott-mariadb:3306

        #######################
        # Configure PhotoPrism: https://github.com/photoprism/photoprism-docs/blob/master/docs/getting-started/config-options.md
        #   public server URL incl http:// or https:// and /path, :port is optional
        - name: PHOTOPRISM_SITE_URL
          value: "https://photos.scott.willeke.com/" # public server URL incl http:// or https:// and /path, :port is optional
        - name: PHOTOPRISM_SITE_CAPTION
          value: "Scott's Photos"
        - name: PHOTOPRISM_SITE_TITLE
          value: "Scott's Photos"
        - name: PHOTOPRISM_SITE_DESCRIPTION
          value: "Various photographs from Scott" # meta site description
        - name: PHOTOPRISM_SITE_AUTHOR
          value: "Scott Willeke" # meta site author
        
        # enable debug mode, show non-essential log messages
        #- name: PHOTOPRISM_DEBUG
        #  value: "true"        

      # pod-level volumes:
      volumes:
        - name: import
          hostPath:
            path: /mnt/thedatapool/photos/scott/import
        - name: originals
          hostPath:
            path: /mnt/thedatapool/photos/scott/organized-originals
        - name: storage
          hostPath:
            path: /mnt/thedatapool/app-data/photoprism-scott/app/storage
