resources:
  - ./home-assistant-namespace.yaml
  - ./base/zwavejs-statefulset.yaml
  - ./base/zwavejs-service.yaml
  - ./base/home-assistant-statefulset.yaml
  - ./base/home-assistant-service.yaml

#buildMetadata: [originAnnotations, transformerAnnotations]

commonLabels:
  # NOTE: metrics-server seems to label all of their resources with `k8s-app: metrics-server`
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: home-assistant