resources:
  - namespace.yaml
  - app-ingress-certificate.yaml
  - ../../base

patches:
  - path: patch-db-pv-volume.yaml
  - path: patch-rabbitmq-pv-volume.yaml
  - path: patch-app-ingress.yaml

namespace: tayle-prod

secretGenerator:
  - name: db-creds
    envs:
      - db-credentials.secrets
  - name: rabbitmq-creds
    envs:
      - rabbitmq-credentials.secrets
  - name: app-creds
    envs:
      - service-shared-credentials.secrets
      - app-credentials.secrets
  - name: worker-creds
    envs:
      - service-shared-credentials.secrets
      - worker-credentials.secrets

# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_imagetagtransformer_
images:
- name: tayle-image-app
  newName: ghcr.io/activescott/tayle/app
  newTag: pr-9-9f2666b # replace this tag to update app
- name: tayle-image-worker
  newName: ghcr.io/activescott/tayle/worker
  newTag: pr-9-9f2666b # replace this tag to update worker
- name: tayle-image-db
  newName: postgres
  newTag: "17"
- name: tayle-image-rabbitmq
  newName: rabbitmq
  newTag: 3-management
