# NOTE: We use ingress here rather than a simple service so we can route traffic
#   based on hostname and not only IP. Ingress also has the advantage of being
#   able to serve TLS.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tayle-app-ingress
spec:
  tls:
  - hosts:
      - app.tayle.co
    secretName: app-tayle-co-tls
