resources:
  - ./base/secret-editor-sa-role-and-binding.yaml
  - ./base/letsencrypt-secret-loader-cronjob.yaml

buildMetadata: [managedByLabel]

labels:
  - pairs:
      deployedBy: scott-via-kustomize
