# kinda like: https://cert-manager.io/docs/tutorials/acme/nginx-ingress/
# test deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-certificateissuer
spec:
  selector:
    matchLabels:
      app: test-certificateissuer
  replicas: 1
  template:
    metadata:
      labels:
        app: test-certificateissuer
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        name: kuard
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-certificateissuer-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: test-certificateissuer
---
# test ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-certificateissuer-ingress
  annotations:
    #cert-manager.io/issuer: "letsencrypt-staging"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - photos.scott.willeke.com
    secretName: photos-scott-willeke-com-tls
  rules:
  - host: photos.scott.willeke.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-certificateissuer-service
            port:
              number: 80
