# NOTES:
# - cert-manager resources already have a namespace defined in cert-manager for namespaced resources (some like their CRDs are not namespaced) 
# - cert-manager resources uses the app label already and not all of the resources are under app: cert-manager (e.g. some are `app: cainjector`)
resources:
- ./overlays/prod

buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: cert-manager
  app.activescott.com/tenant: anyone
