resources:
- ../../base/

patches:
  # patch resource limits on the three deployments
  # good reference for patches: https://fabianlee.org/2022/04/15/kubernetes-kustomize-transformations-with-patchesjson6902/
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            memory: "64Mi"
          requests:
            memory: "32Mi"
    target:
        kind: Deployment
        labelSelector: "app=cainjector,app.kubernetes.io/component=cainjector"

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            memory: "96Mi"
          requests:
            memory: "64Mi"
    target:
        kind: Deployment
        labelSelector: "app=cert-manager,app.kubernetes.io/component=controller"

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            memory: "64Mi"
          requests:
            memory: "32Mi"
    target:
        kind: Deployment
        labelSelector: "app=webhook,app.kubernetes.io/component=webhook"