resources:
- ./namespace.yaml
- ../../base


patches:
# patch Ingress.tls hostname:
- target:
    kind: Ingress
    name: nextcloud-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: files.activescott.com
# patch Ingress rules
- target:
    kind: Ingress
    name: nextcloud-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: files.activescott.com
# super lame, but we have to add the K8S namespace to the traefik middlewares here (i.e. prefix each with "nextcloud-prod-")
- target:
    kind: Ingress
    name: nextcloud-ingress
  patch: |-
    - op: replace
      path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
      value: nextcloud-prod-well-known-carddav@kubernetescrd,nextcloud-prod-well-known-caldav@kubernetescrd,nextcloud-prod-well-known-webfinger@kubernetescrd,nextcloud-prod-well-known-nodeinfo@kubernetescrd


secretGenerator:
- name: db-creds-for-nextcloud
  envs:
  - .env.secret.db-creds-for-nextcloud
- name: db-creds-for-mariadb
  envs:
  - .env.secret.db-creds-for-mariadb
- name: nextcloud-admin-creds
  envs:
  - .env.secret.nextcloud-admin-creds


namespace: nextcloud-prod
